# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20161030_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
