# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20161031_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
