# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20161118_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
