# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views_number',
        ),
    ]
